# Generated by Django 2.2 on 2021-03-31 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentsregistrationmodel',
            name='phone_number',
            field=models.CharField(max_length=10, verbose_name='Phone Number'),
        ),
    ]
