# Generated by Django 2.2 on 2021-03-31 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0003_auto_20210331_1232'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentsregistrationmodel',
            name='sex',
            field=models.CharField(choices=[('F', 'Female'), ('M', 'Male'), ('O', 'Other')], default='Select', max_length=1),
        ),
    ]
