# Generated by Django 2.2 on 2021-03-31 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0006_auto_20210331_1433'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentsregistrationmodel',
            name='sex',
            field=models.CharField(choices=[('A', 'Select'), ('F', 'Female'), ('M', 'Male'), ('O', 'Other')], max_length=1),
        ),
    ]
