# Generated by Django 2.2 on 2021-03-31 09:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0007_auto_20210331_1445'),
    ]

    operations = [
        migrations.RenameField(
            model_name='studentsregistrationmodel',
            old_name='sex',
            new_name='gender',
        ),
    ]
