# Generated by Django 2.2 on 2021-03-31 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0008_auto_20210331_1446'),
    ]

    operations = [
        migrations.AlterField(
            model_name='country_model',
            name='country',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='state',
            name='name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='studentsregistrationmodel',
            name='gender',
            field=models.CharField(choices=[('F', 'Female'), ('M', 'Male'), ('O', 'Other')], default=None, max_length=1),
        ),
    ]
