# Generated by Django 2.2 on 2021-03-31 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0009_auto_20210331_1536'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentsregistrationmodel',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
    ]
