# Generated by Django 2.2 on 2021-03-31 12:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0010_auto_20210331_1728'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentsregistrationmodel',
            name='dob',
        ),
    ]
